module.exports = {
  'post /agol': 'register',
  'get /agol': 'list',
  'get /agol/queue/length': 'getQueueLength',
  'get /agol/queue/workers': 'getQueueWorkers',
  'get /agol/queue/working': 'getQueueWorkingCount',
  'get /agol/queue/clearFailed': 'clearFailedJobs',
  'get /agol/:id': 'find',
  'get /agol/:id/:item/*': 'setHostKey',
  'put /agol/:id/:item/*': 'setHostKey',
  'post /agol/:id/:item/*': 'setHostKey',
  'get /agol/:id/:item': 'getInfo',
  // this method needs to come before layer/format
  'get /agol/:id/:item/FeatureServer': 'featureserver',
  // end method that needs to be before layer/format
  'delete /agol/:id': 'del',
  'delete /agol/:id/:item/:layer': 'deleteItemData',
  'get /agol/:id/:item/:layer/geohash': 'getGeohash',
  'get /agol/:id/:item.:format': 'getResource',
  'get /agol/:id/:item/:layer.:format': 'getResource',
  'get /agol/:id/:item/:layer': 'getInfo',
  'get /agol/:id/:item/:layer/drop': 'dropResource',
  'get /agol/:id/:item/:layer/tiles/:z/:x/:y.:format': 'tiles',
  'get /agol/:id/:item/:layer/tiles/:z/:x/:y': 'tiles',
  'get /agol/:id/:item/FeatureServer/geohash': 'getGeohash',
  'get /agol/:id/:item/FeatureServer/:layer': 'featureserver',
  'get /agol/:id/:item/FeatureServer/:layer/geohash': 'getGeohash',
  'get /agol/:id/:item/FeatureServer/:layer/:method': 'featureserver',
  'post /agol/:id/:item/FeatureServer/:layer/:method': 'featureserver',
  'get /agol/:id/:item/:layer/expiration': 'getExpiration',
  'put /agol/:id/:item/:layer/expiration': 'setExpiration',
  'post /agol/:id/:item/:layer/expiration': 'setExpiration',
  'get /test': 'testRoute'
}
